require "clamp"

require_relative "../common/cli/version_command"
require_relative "cli/run_command"
require_relative "cli/stream_command"
require_relative "cli/yield_command"
require_relative "cli/ps_command"
require_relative "cli/kill_command"
require_relative "cli/rm_command"
require_relative "cli/spawn_command"
require_relative "cli/signal_command"
require_relative "cli/attach_command"
require_relative "cli/stdout_command"

require_relative "cli/root_command"
